### ISSUE TITLE
It would be nice to auto-merge pull requests initiated by updatebot from Jenkins pipelines

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2157]
so, that developers don't have to wait for manual review to merge `updatebot` pull requests into release branch, i.e. https://github.com/Activiti/activiti-cloud-api/pull/26 that will need to propagate into activiti-cloud-dependencies.

There is a useful Github app called https://mergify.io. We can just signup and authorize mergify.io to babysit pull requests for subscribed repositories:

![image](https://user-images.githubusercontent.com/20428629/48460449-e3009b80-e783-11e8-9425-bfcb5f9e93b9.png)

Then. we just drop the following `.mergify.yml` file into each repository to specify conditions for automatic merge and delete of the PR branch:

```yaml
pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - author=jx-activiti-cloud
      - status-success=continuous-integration/jenkins/pr-head
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=license/cla
    actions:
      delete_head_branch: {}
      merge:
        method: squash
        strict: true
```

This configuration will enable strict merge workflow: https://doc.mergify.io/strict-workflow.html with squash merge as single PR commit

![image](https://user-images.githubusercontent.com/20428629/48460460-edbb3080-e783-11e8-926b-339f1ab514f6.png)

When the strict workflow is enabled, Mergify takes care of merging the target branch in any pull request that is not up-to-date with its target branch. If multiple pull requests are mergeable, they are scheduled to be merged sequentially, and they will be updated on top of each other.

The pull request branch update is only done when the pull request is ready to be merged by the engine, e.g., when the status checks are OK and the number of postive reviews are enough.
