### ISSUE TITLE
Enable single pull request merge for updatebot configurations in activiti-dependencies repository

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2167]
So, that we can validate and enforce consistent versions across upstream modules in CI/CD pipelines for automated PR merge with Mergify.io

We will need to ensure same versions for `activiti-build` and `activiti-core-common` and `activiti-api` using Maven enforcer 

We need to check that Jenkins-X uses Maven builder image with updatebot v1.1.27+ and update .updatebot.yml in each upstream repository to push versions vai single pull request in `activiti-dependencies`:

Tasks:

- [x] enable and test Maven enforcer plugin configurations in `activiti-dependencies` pom.xml
- [x] check updatebot version is v1.1.27+ in Jenkins-X cluster and upgrade Jx platform to latest version
- [x] add `useSinglePullRequest: true` for `activiti-dependecies` in `activiti-api`, `activiti-core-common`, activiti-build in `.updatebot.yml`
- [x] Push both activiti-build and activiti-dependencies versions into activiti-examples 
- [x] remove activiti-build parent from activiti-dependencies
- [x] Realign activiti-dependencies updatebot with cloud dependencies
- [x] Deploy modules at the end of the multi-module build in activiti-dependencies.

```yaml
github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-dependencies
      branch: develop
      useSinglePullRequest: true
```

![image](https://user-images.githubusercontent.com/20428629/48571879-d59afc80-e8bc-11e8-9833-286e51e52960.png)
