### ISSUE TITLE
Let's configure updatebot single PR for Activiti Cloud with automated merging using Mergify.io

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2196]
We will configure automatic merges for updatebot PRs across Activiti Cloud repositories with single PR into Activiti-Cloud Dependencies aggregator PoM in order to enforce version convergence for its release:

### .updatebot.yml
```yaml
github:
  organisations:
  - name: activiti 
    repositories:
    - name: activiti-cloud-dependencies
      branch: develop
      useSinglePullRequest: true 
```

### Activiti Cloud Build Graph
![image](https://user-images.githubusercontent.com/20428629/48916850-cf66cc00-ee38-11e8-864d-657de873b6da.png)

### Activiti Cloud Modeling Build Graph
![image](https://user-images.githubusercontent.com/20428629/48918421-3daf8c80-ee41-11e8-89ea-629b10c44c4c.png)

We will also configure Mergify.io robot to automatically merge PRs generated by updatebot in order to propagate versions across dependencies that pass status checks using strict merge:

### .mergify.yml
```yaml
pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - author=jx-activiti-cloud
      - status-success=continuous-integration/jenkins/pr-head
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=license/cla
    actions:
      delete_head_branch: {}
      merge:
        method: merge
        strict: true
  - name: automatic merge when CI passes and 1 approving reviews
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=continuous-integration/jenkins/pr-head
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=license/cla
    actions:
      delete_head_branch: {}
      merge:
        method: squash
        strict: true
```
