### ISSUE TITLE
Let's add do-not-merge label condition for Mergify.io

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2215]
so, that we can control the gates when not to merge the PRs created by updatebot.  

Adding `do-not-merge` label for open PR will simply disable the automatic merge when the status checks are green. This can be useful to indicate that a pull request labelled as work-in-progress should not be merged.

```yaml
pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - author=jx-activiti-cloud
      - status-success=continuous-integration/jenkins/pr-head
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=license/cla
      - label!=do-not-merge
    actions:
      delete_head_branch: {}
      merge:
        method: merge
        strict: true
```
