### ISSUE TITLE
Let's customize Activiti Cloud Jenkins-X pipelines to build Docker images with DinD 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2224]
sidecar container so, that

- Docker daemon on VM host is fully secured and isolated from Jenkins X builder pods.
- Concurrent Jenkins X pipeline Docker builds and CI tests are fully isolated from each other.
- CI Docker containers are deleted by Kubernetes when Pod is deleted
- CI Docker containers are accessible by CI tests via http://localhost:port inside Maven builder container.
- Docker graph storage space is reclaimed by Kubernetes when Pod is deleted
- Skaffold will build images using sidecar Dind daemon and push images to public docker.io registry
- Dind daemon will use Google gcr.io as registry mirror for pulling cached images. 

We will setup DinD sidecar container by customizing Jenkinsfile agent with additional pod spec to override and map DOCKER_HOST in Maven builder container to use Docker daemon in DinD container:

![image](https://user-images.githubusercontent.com/20428629/49265031-7503d780-f405-11e8-853d-e56e4874396b.png)

More details to follow....

**Comment by salaboy** [comment]
@igdianov do you roughly know what are the changes in the pipelines?

**Comment by igdianov** [comment]
@salaboy These are going to be the changes in Jenkinsfile:

```Jenkinsfile
  agent {
   - label "jenkins-maven"
   + kubernetes {
   +    // Change the name of jenkins-maven label to be able to use yaml configuration snippet
   +   label "maven-dind"
   +     // Inherit from Jx Maven pod template
   +     inheritFrom "maven"
   +     // Add pod configuration to Jenkins builder pod template
   +    yamlFile "maven-dind.yaml"
   +  } 
  }
```
add maven-dind.yaml:

```yaml
spec:
  volumes:
  - name: docker-daemon
    emptyDir: {}
  - name: jenkins-docker-cfg-volume
    secret:
      secretName: jenkins-docker-cfg
  containers:
  # Override Docker config in Maven to use DinD 
  - name: maven
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    volumeMounts:
    - mountPath: /var/lib/docker  
      name: docker-daemon
  # Create sidecar container with DinD to build docker images
  - name: dind
    image: docker:18.06.1-dind
    imagePullPolicy: IfNotPresent
    args:
    - --registry-mirror=https://mirror.gcr.io
    workingDir: /home/jenkins
    securityContext:
      privileged: true
    tty: true
    env:
    - name: DOCKER_CONFIG
      value: /home/jenkins/.docker/ 
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    - name: DOCKER_REGISTRY
      valueFrom:
        configMapKeyRef:
          name: jenkins-x-docker-registry
          key: docker.registry
    resources:
      requests:
        cpu: 512m
        memory: 1024Mi
      limits:
        cpu: 1
        memory: 2048Mi
    volumeMounts:
    - mountPath: /home/jenkins
      name: workspace-volume
    - mountPath: /var/lib/docker  
      name: docker-daemon
    - mountPath: /home/jenkins/.docker
      name: jenkins-docker-cfg-volume
      readOnly: true  
```
