### ISSUE TITLE
Let's configure preemptive node pool to run activiti-cloud-acceptance-scenarios 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2276]
so that we have enough resources to deploy preview chart for acceptance scenarios in separate node pool with cheap fat preemptive instances and auto-scaling to run acceptance scenarios pipelines

First, we create new node pool called `jenkins-x-builders` in GKE cluster with Preemptible nodes and Autoscaling options enabled. The node size should be minimum 8 CPU's or bigger to accommodate heavy workloads.  We must also add `NO_SCHEDULE:gke-preemtible=true` taint when creating the node pool in order to avoid scheduling other regular pods on preemptible nodes.

GKE  will automatically add `cloud.google.com/gke-preemptible` label to each node instance so we can use it in our pipeline's Kubernetes agent's customization yamlFile to specify `nodeSelector` and taint `tolerations`:

gke-preemtible.yaml:

```yaml
spec:
  # The node selector says that pod must be scheduled only on nodes that have specific label and value. 
  nodeSelector:
    cloud.google.com/gke-preemptible: "true"
    
  # It is necessary to add toleration to GKE preemtible pool taint to the pod spec in order to schedule it on preemptible nodes
  tolerations:
  - key: "gke-preemptible"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"        
```

We also need to change Jenkinsfile pipeline with Kubernetes Plugin configuration to use our gke-preemptible customization:

```
pipeline {
    agent {
       kubernetes {
              // Change the name of jenkins-maven label to be able to use yaml configuration snippet
              label "maven-gke-preemptible"
              // Inherit from Jx Maven pod template
              inheritFrom "maven"
              // Add pod configuration to Jenkins builder pod template
              yamlFile "gke-preemtible.yaml"
            }
    }
```

Node labels and tolerations for pod assignment reference:

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
