### ISSUE TITLE
keycloak and gateway on same host

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2451]
We tried this before and found we needed to [set PROXY_ADDRESS_FORWARDING](http://lists.jboss.org/pipermail/keycloak-user/2018-July/014471.html). I think others hit problems too as the new official keycloak chart includes this change - https://github.com/helm/charts/commit/b849a0845b782c18b54d2b315697fb3f633316fb#diff-ca4abb7301f7a55b818df1c424dc153d  

To get that change we should [switch to alfresco identity service](https://github.com/Activiti/Activiti/issues/2450) as it is wrapping the keycloak chart (and a newer version)

**Comment by igdianov** [comment]
@ryandawsonuk We also need to set PROXY_ADDRESS_FORWARDING for HTTPS to work with Nginx proxy. So, it may be a good idea to always set to true and allow opt out option just in case...

**Comment by igdianov** [comment]
@ryandawsonuk I have validated the following changes to Keycloak configuration in order to make keycloak and gateway work on same host. I think it would be best to override and template the Keycloak ingress to inject gateway host values without so many change in the values.yaml:

```
global:
  keycloak:
    # -+ replace with gateway.host value 
    url: "http://activiti-cloud-gateway.jx-staging.35.197.40.115.nip.io/auth" 
  gateway: 
    host: &gatewayhost "activiti-cloud-gateway.jx-staging.35.197.40.115.nip.io"

activiti-keycloak:
  keycloak:
    enabled: true
    keycloak:
      extraEnv: |
        - name: KEYCLOAK_LOGLEVEL
          value: DEBUG
        - name: WILDFLY_LOGLEVEL
          value: DEBUG
        # + Add this variable. We will need this for TLS 
        - name: PROXY_ADDRESS_FORWARDING anyway
          value: "true"
      ingress:
        enabled: true
        # -+ Replace Ingress path 
        path: /auth 
        proxyBufferSize: "16k"
        hosts:
         # + Point to gateway.host 
          - *gatewayhost
        annotations:
          kubernetes.io/ingress.class: nginx
         # - Remove rewrite-path annotation. We should not be using this...
#          nginx.ingress.kubernetes.io/rewrite-path: / 
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers 'Access-Control-Allow-Methods: "POST, GET, OPTIONS, PUT, PATCH, DELETE"';
            more_set_headers 'Access-Control-Allow-Credentials: true';
            more_set_headers 'Access-Control-Allow-Headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,authorization"';
            more_set_headers 'Access-Control-Allow-Origin: $http_origin';
          nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      preStartScript: |
        /opt/jboss/keycloak/bin/add-user.sh -u admin -p admin
        /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin
        cp /realm/activiti-realm.json .
        sed -i 's/placeholder.com/*/g' activiti-realm.json

```
