### ISSUE TITLE
services to use different schemas in shared postgres

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2479]
a follow-up on https://github.com/Activiti/Activiti/issues/2431

**Comment by knowings** [comment]
For the record, I tried a naive approche by simply changing the database name in SPRING_DATASOURCE_URL env variable within my Kubernetes deployment file. It fails to start then, complaining about the missing database.

**Comment by knowings** [comment]
I managed to get it working from within a Kubernetes deployment file. I simply add an `initContainer` like the following `wait-for-postgresql-database`:

```yaml
initContainers:
      - command:
        - sh
        - -c
        - |
          until printf "." && nc -z -w 2 tardis-postgres 5432; do
              sleep 2;
          done;

          echo 'PostgreSQL OK Ô£ô'
        image: alpine:3.8
        imagePullPolicy: IfNotPresent
        name: wait-for-postgresql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: jbergknoff/postgresql-client
        imagePullPolicy: IfNotPresent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        name: wait-for-postgresql-database
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password
                name: some-postgres
        command:
          - psql
          - postgresql://postgres@some-postgres:5432
          - -c
          - |
            CREATE DATABASE somedbname;
```
Note, I'm not sure how it behaves after a deletion of the pod.

**Comment by knowings** [comment]
Ok, now it should work with an `initContainer` like the following:

```yaml
- image: jbergknoff/postgresql-client
        imagePullPolicy: IfNotPresent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        name: wait-for-postgresql-schema
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password
                name: some-postgres
        command:
          - sh
          - -c
          - |
            psql postgresql://postgres@some-postgres:5432 -tc "SELECT 1 FROM pg_database WHERE datname = 'somedbname'" | grep -q 1 || psql postgresql://postgres@some-postgres:5432 -c "CREATE DATABASE somedbname"
```
It's not the most elegant way to do the trick, but it seems to work even when pod is reinitializing.
