### ISSUE TITLE
Enable Rabbitmq persistentVolume in activiti-cloud-full-example charts 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2614]
because `rabbitmq-ha` Helm chart does not enable persistent volume out-of-the-box, so restarting rabbitmq pod will cause losing current state of the queues, exchanges and bindings. 

To provision volume use the following Yaml snippet in the application chart.

```yaml
rabbitmq:
  persistentVolume:
    enabled: true
```
