### ISSUE TITLE
Helm Install of activiti-cloud-full-example chart with Helm 2.14.3 fails

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2864]
to create Identity Postgresql volume claim.

**Comment by igdianov** [comment]
The problem  is caused by Helm 2.14.3 regression that fails to override `null` value for existingClaim in https://github.com/Activiti/activiti-cloud-identity-chart/blob/c77449e66f6ec970d2e68eaa581046e5e1bf9d5e/charts/activiti-cloud-identity/values.yaml#L17

**Comment by igdianov** [comment]
It appears that Helm 2.14+ does not remove keys when the value is set to `null`. The workaround should be to set the existingClaim to empty string `""` instead of `null`, i.e. :

```
alfresco-identity-service:
  enabled: true
  ingress:
    enabled: false
  keycloak:
    postgresql:
      persistence:
        existingClaim: "" # use default postgresql PVC
```

When using Helm 2.14 to install any previously published `activiti-cloud full-example` chart, the fix is to add additional key `activiti-cloud-identity.alfresco-identity- service.keycloak.postgresql.persistence.existingClaim=""` via `--set` argument:

```
helm install activiti-cloud-helm-charts/activiti-cloud-full-example \
  --name example \
  --version 7.1.0-M3.1 \
  --set global.gateway.domain=X.X.X.X.nip.io \
  --set activiti-cloud-identity.alfresco-identity- service.keycloak.postgresql.persistence.existingClaim=""

```
