### ISSUE TITLE
Add support for partitioned message streams 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#3639]
For audit producer in the process runtime, it should be aware of how many partitioned consumers are available in order to consistently route messages for the same process instance to the same consumer stream.

For audit and query consumers, they should be aware their instance index across partitions to be able to bind to its message stream.

The deployment configuration support for partitioned messaging should be provided by Helm chart. The partitioned messaging can be activated using global values, i.e.

```yaml
global:
  messaging:
    # global.messaging.broker -- required messaging broker, rabbitmq or kafka
    broker: "rabbitmq"
    # global.messaging.partitioned -- enables partitioned messaging in combination with messaging.enabled=true && messaging.role=producer|consumer
    partitioned: true
    # global.messaging.partitionCount -- configures number of partitioned consumers 
    partitionCount: 2
```

Then, each deployment, should provide values to enable messaging configuration with role value, i.e `producer` or `consumer`:

For producer, i.e. runtime-bundle:
```yaml
messaging: 
  enabled: true
  role: producer
```

For consumer, i.e. activiti-cloud-query:
```yaml
messaging: 
  enabled: true
  role: consumer
```

For connector, i.e. activiti-cloud-connect:
```yaml
messaging: 
  enabled: true
```
