### ISSUE TITLE
how to deploy new processes using spring.activiti.processDefinitionLocationPrefix param

### ISSUE THREAD

**Issue by ilseva** [Activiti/Activiti#3725]
Hi everyone, 
I'm using Activiti 7 (7.1.0-M14) with the example-runtime-bundle of the activiti-cloud-examples project.
I would like to deploy my custom processes and I found the parameter _processDefinitionLocationPrefix_.
I modify the docker-compose mounting a local volume to example-runtime-bundle container as
```yaml
...
example-runtime-bundle:
   environment:
      SPRING_ACTIVITI_PROCESSDEFINITIONLOCATIONPREFIX: file:/opt/processes/
   ...
   volumes:
      - ./processes:/opt/processes
... 
```
Everything works fine at first startup.  
If I put a new process definition in the volume (processes local  folder in my example), stop and start the container, the new process is not deployed.

I try to change the _deploymentMode_ to "single_resource" and the new processes are deployed, but I'm not able to start them (using ReST API) because the `ProcessRuntimeImpl` use a fixed string to search the deployment
```java
@Override
    public Deployment selectLatestDeployment(){
        return deploymentConverter.from(
                repositoryService
                    .createDeploymentQuery()
                    .deploymentName("SpringAutoDeployment")
                    .latestVersion()
                    .singleResult()
        );
    }
```
How can I deploy new processes when the bundle start?
Thanks.
