### ISSUE TITLE
Automatically create GH pre-releases for `alpha` and `rc` tags

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#4108]
Automatically create GH pre-releases for `alpha` and `rc` tags. To facilitate the logic of main releases, a `release.yaml` asset will be attached to the GH release on `ativiti-cloud` and `activiti-cloud-application`.

activiti-cloud:
```yaml
release:
  baseTag:
    activiti: 7.6.0-alpha.4
    activitiCloud: 7.6.0-alpha.11
```

activiti-cloud-application:
```yaml
release:
  baseTag:
    activiti: 7.6.0-alpha.4
    activitiCloud: 7.6.0-alpha.11
    activitiCloudApplication: 7.6.0-alpha.12
```
