### ISSUE TITLE
activiti-spring-boot-starter 7.1.0.M3.1 h2 Unknown data type IDENTITY

### ISSUE THREAD

**Issue by duhbbx** [Activiti/Activiti#4192]
### activiti version

```xml
<dependency>
    <groupId>org.activiti</groupId>
    <artifactId>activiti-spring-boot-starter</artifactId>
    <version>7.1.0.M3.1</version>
</dependency>
```

### JDK

jdk 1.8

### yaml

```yml
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: audit
```

## Error

```sql
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Unknown data type: "IDENTITY"; SQL statement:
create table ACT_EVT_LOG ( 
LOG_NR_ identity, 
TYPE_ varchar(64), 
PROC_DEF_ID_ varchar(64), 
PROC_INST_ID_ varchar(64), 
EXECUTION_ID_ varchar(64), 
TASK_ID_ varchar(64), 
TIME_STAMP_ timestamp not null, 
USER_ID_ varchar(255), 
DATA_ longvarbinary, 
LOCK_OWNER_ varchar(255), 
LOCK_TIME_ timestamp, 
IS_PROCESSED_ bit default 0 
)
```
